#!/usr/bin/env python3
"""Build NOTICES.md — aggregated third-party license attribution (story-third-party-notices).

Walks scripts/_notices_catalog.CATALOG (pinned components: Python deps + install.sh
binaries + spaCy model + uv), renders each as a Markdown section with name | version |
SPDX | URL | copyright, and emits a SUMMARY grant clause for GPL-2/GPL-3/AGPL-3
components pointing readers to the canonical upstream LICENSE text.

To add a new component: append a `Component(...)` to scripts/_notices_catalog.CATALOG;
its SPDX must appear in SUPPORTED_SPDX. GPL-2 / GPL-3 / AGPL-3 components auto-emit
a summary grant clause via `_grant_for`.

Exit 0 on success; 1 on `UNKNOWN_LICENSE:<name>`.
"""

from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from _notices_catalog import CATALOG, SUPPORTED_SPDX, Component  # noqa: E402

# License-grant summaries — paraphrased preambles pointing to the canonical
# upstream LICENSE text. NOT the verbatim full-license text. The full license is
# at the URL shown alongside each summary; auditors should consult that.
_GPL3_SUMMARY = (
    "This program is free software: you can redistribute it and/or modify it "
    "under the terms of the GNU General Public License (version 3) as published "
    "by the Free Software Foundation. Full license text: "
    "<https://www.gnu.org/licenses/gpl-3.0.html>."
)
_GPL2_SUMMARY = (
    "This program is free software; you can redistribute it and/or modify it "
    "under the terms of the GNU General Public License (version 2) as published "
    "by the Free Software Foundation. Full license text: "
    "<https://www.gnu.org/licenses/gpl-2.0.html>."
)
_AGPL3_SUMMARY = (
    "This program is free software: you can redistribute it and/or modify it "
    "under the terms of the GNU Affero General Public License (version 3) as "
    "published by the Free Software Foundation. Full license text: "
    "<https://www.gnu.org/licenses/agpl-3.0.html>."
)


def _grant_for(spdx: str) -> str | None:
    return {
        "GPL-3.0-only": _GPL3_SUMMARY,
        "GPL-2.0-only": _GPL2_SUMMARY,
        "AGPL-3.0-only": _AGPL3_SUMMARY,
    }.get(spdx)


def _render_component(c: Component) -> str:
    lines = [
        f"## {c.name}",
        "",
        f"- Version: {c.version}",
        f"- SPDX: {c.spdx}",
        f"- Source: <{c.url}>",
        f"- Copyright: {c.copyright}",
    ]
    grant = _grant_for(c.spdx)
    if grant:
        lines += [
            "",
            f"Summary grant clause ({c.spdx}, see Source URL for full text):",
            "",
            f"> {grant}",
        ]
    return "\n".join(lines) + "\n"


def _render(components: tuple[Component, ...]) -> str:
    head = [
        "# NOTICES",
        "",
        "SilentWitness is licensed under MIT (see [LICENSE](./LICENSE)).",
        "",
        "This NOTICES file aggregates third-party attributions per their respective licenses.",
        "Generated by `scripts/build_notices.py`; do not edit by hand.",
        "",
        "## About this file",
        "",
        "Each entry below names a third-party component bundled, installed, or",
        "subprocess-invoked by SilentWitness, with its version pin, SPDX license",
        "identifier, canonical source URL, and copyright holder.",
        "",
        "**Linkage analysis:** All listed binary tools (Hayabusa, Chainsaw, Velociraptor,",
        "Zeek, Suricata, Volatility 3, MFTECmd) are subprocess-invoked from SilentWitness;",
        "there is no static linking, no derived-work conveyance, and (for Velociraptor's",
        "AGPL-3.0 trigger) no remote network service is exposed to third parties.",
        "Python dependencies are linked at import time; their licenses are MIT / BSD /",
        "Apache-2.0 / VSL, none of which impose copyleft obligations on the consumer.",
        "",
        "**Grant clauses below are paraphrased summaries** pointing to the canonical",
        "upstream LICENSE text at the Source URL. For license-compliance audits, consult",
        "the full text at the upstream URL, not the summary here.",
        "",
    ]
    sorted_components = sorted(components, key=lambda c: c.name.lower())
    body = [_render_component(c) for c in sorted_components]
    return "\n".join(head) + "\n".join(body)


def build(catalog: tuple[Component, ...]) -> str:
    """Validate SPDX + render NOTICES.md text. Raises ValueError on UNKNOWN_LICENSE."""
    for c in catalog:
        if c.spdx not in SUPPORTED_SPDX:
            raise ValueError(f"UNKNOWN_LICENSE: {c.name} ({c.spdx!r})")
    return _render(catalog)


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Build NOTICES.md.")
    parser.add_argument("--out", type=Path, default=Path("NOTICES.md"))
    parser.add_argument(
        "--inject-unknown",
        default=None,
        help=(
            "[TEST-ONLY] Inject a bogus SPDX component to verify the exit-1 "
            "failure path; never use in production builds."
        ),
    )
    args = parser.parse_args(argv)

    catalog = CATALOG
    if args.inject_unknown:
        catalog = (
            *catalog,
            Component(
                args.inject_unknown,
                "0.0",
                "Mystery-License-9000",
                "https://example.invalid",
                "Copyright (c) ?",
            ),
        )
    try:
        text = build(catalog)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
